export const FETCH_COURSES_DATA_LIST = 'FETCH_COURSES_DATA_LIST';
export const FETCH_COURSES = 'FETCH_COURSES';
export const FETCH_EVALUATION = 'FETCH_EVALUATION';

export const SET_SEMESTER_LIST = 'SET_SEMESTER_LIST';
export const SET_COURSES = 'SET_COURSES';
export const SET_EVALUATION = 'SET_EVALUATION';
